server:
    url: server_url
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: 
        - en-US
        - fr-CH
    cors: true
    pretty_print: true
    limit: 10
    ogc_schemas_location: /schemas.opengis.net

logging:
    level: ERROR

metadata:
    identification:
        title: 
            en: Serveur title
            fr-CH: Titre du serveur
        description: 
            en: Serveur description
            fr-CH: Description du serveur
        keywords:
            en:
                - keyword#1
                - keyword#2
                - keyword#3
        terms_of_service: https://creativecommons.org/licenses/by/3.0/
        url: organization url
    license:
        name: CC-BY 3.0 license
        url: https://creativecommons.org/licenses/by/3.0/ch/deed.en
    provider:
        name: Provider Name
        url: provider url
    contact:
        name: Contact Name
        position: Position Title
        address: Address of Organization
        city: city
        stateorprovince: state
        postalcode: postalcode
        country:  country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: contact email
        url: organization url
        hours: Hours of Service
        instructions: During hours of service. Off on weekends
        role: pointOfContact

resources:
# Collection #1
  images_location:
    type: collection
    lang: en-US
    title: collection_title
    description: "Collecton description"
    keywords:
      - keyword#1
      - keyword#2  
      - keyword#3  
    links:
      - type: text/html
        rel: canonical
        title: information
        href: company_url
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180,-90,180,90] 
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          schema: schema_name
          id_field: id_field
          table: table_name
          geom_field: geom_field_name
